name: Automated QA with Playwright

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  qa-playwright:
    name: Run QA for DataDash - 24f2007947@ds.study.iitm.ac.in
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install playwright

      - name: Run Playwright Script
        run: node scrapeAndSum.mjs
